
naExclude_tt_title  <-  "Exclude rows that have only missing values in the selected columns"
reset_cluster_tt_title  <-  "Reset cluster"
reset_region_tt_title  <-  "Reset region"
order_gene_tt_title  <-  "Order by gene"
clinic_tt_title  <-  "<strong>Pearson correlation between the exact N-terminus and clinical parameters in the cross-sectional cohort<\\strong>"
lfc_tt_title  <-  "<strong>SLE_CTRL_CROSS_SECTIONAL</strong><br>log2 fold change for the exact N-terminus between SLE/CTRL from the cross-sectional cohort<br><br><strong>RESPONDERS_NONRESPONDERS_LONGIT</strong><br>log2 fold change between responders and non-responders from the longitudinal cohort"
proteome_tt_title  <-  "<strong>PROT_SLE_CTRL_CROSS_SECT</strong><br>Whole-protein log2 fold change between SLE/CTRL in the cross-sectional cohort"
vitro_tt_title  <-  "<strong>In-vitro digest of EDTA-plasma from CTRL patients</strong><br><br><strong>MASP1_Trypsin</strong><br>log2 fold change between MASP1 and trypsin<br><br><strong>MASP1_GluC</strong><br>log2 fold change between MASP1 and GluC<br><br><strong>MASP3_Trypsin</strong><br>log2 fold change between MASP3 and trypsin<br><br><strong>MASP3_GluC</strong><br>log2 fold change between MASP3 and GluC<br><br><strong>C1r_GluC</strong><br>log2 fold change between C1r and GluC<br><br><strong>C1s_GluC</strong><br>log2 fold change between C1s and GluC<br><br><strong>C1s_Trypsin</strong><br>log2 fold change between C1s and trypsin<br><br><strong>C1r_Trypsin</strong><br>log2 fold change between C1r and trypsin"
mofa_tt_title  <-  "<strong>Factors from the MOFA analysis of the cross-sectional SLE cohort N-terminome and proteome data</strong><br><br>Factors 1, 3, 5, 7 and 10 were driven by N-termini"
ecu_tt_title  <-  "<strong>Log2 FoldChanges between different timepoints of Eculizumab-treated pediatric STEC-HUS patients</strong>"
count_tt_title  <-  "<strong>Number of cross-sectional cohort patients in which the selected N-termini were identified</strong>"
filter_tt_title  <-  "<strong>Filter rows based on in-vitro data</strong><br>For the in-vitro data, only values with a logFC > 0.058 and a P.Value < 0.05 are shown. The rest are replaced with NA<br>This filter removes all rows with only missing values in the in-vitro columns"
cluster_rows_tt_title  <-  "<strong>Cluster rows by Gower\\'s distance and the complete linkage method</strong><br>Clustering is based on the selected columns and N-termini"
slider_tt_title  <-  "This slider allows you to select N-termini that occur within a particular amino acid region of the chosen protein(s)"
